# load up all the builtin rabal/plugins
require 'rabal/plugin/bin'
require 'rabal/plugin/core'
require 'rabal/plugin/ext'
require 'rabal/plugin/foundation'
require 'rabal/plugin/license'
require 'rabal/plugin/rubyforge'
require 'rabal/plugin/spec'
require 'rabal/plugin/test'
require 'rabal/plugin/website'
